author: Clark's Acoustics
description: Suspension ceiling grid systems and sound absorption systems.
email: clark@clarksacoustics.com
title: Clark's Acoustics
url: https://clarksacoustics.com

remote_theme: daattali/beautiful-jekyll
remove-ads: true

avatar: /assets/images/clark.jpg
round-avatar: true
url-pretty: clarksacoustics.com

site-css:
  - /assets/css/main.css

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      ext-css: "https://fonts.googleapis.com/css?family=Noto+Sans"
      footer-extra: footer-extra.html

navbar-links:
  Portfolio: portfolio
  Contact: contact

navbar-extra: navbar-extra.html

plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
